struct LIST_ENTRY32;
struct LIST_ENTRY64;
struct _CONTROLLER_OBJECT;
struct _DESCRIPTION_HEADER;
struct _FACS;
struct _FADT;
struct _GENERAL_LOOKASIDE;
struct _GEN_ADDR;
struct _IOAPIC;
struct _IOSAPIC;
struct _IO_NMISOURCE;
struct _ISA_VECTOR;
struct _KDEVICE_QUEUE;
struct _LIST_ENTRY;
struct _LOCAL_NMISOURCE;
struct _MAPIC;
struct _NPAGED_LOOKASIDE_LIST;
struct _OBJECT_ATTRIBUTES;
struct _OBJECT_TYPE;
struct _PAGED_LOOKASIDE_LIST;
struct _PLATFORM_INTERRUPT;
struct _PROCLOCALAPIC;
struct _PROCLOCALSAPIC;
struct _RSDP;
struct _RSDT_32;
struct _RTL_BITMAP;
struct _SLIST_HEADER;
struct _UNICODE_STRING;

union _LARGE_INTEGER;
union _ULARGE_INTEGER;

enum _INTERLOCKED_RESULT;
enum _MEMORY_CACHING_TYPE_ORIG;
enum _MEMORY_TYPE;
enum _POOL_TYPE;

typedef struct LIST_ENTRY32 {
    ULONG Flink;
    ULONG Blink;
};

typedef struct LIST_ENTRY64 {
    ULONG64 Flink;
    ULONG64 Blink;
};

typedef struct _CONTROLLER_OBJECT {
    SHORT Type;
    SHORT Size;
    PVOID ControllerExtension;
    struct _KDEVICE_QUEUE DeviceWaitQueue;
    ULONG Spare1;
    union _LARGE_INTEGER Spare2;
};

typedef struct _DESCRIPTION_HEADER {
    ULONG Signature;
    ULONG Length;
    UCHAR Revision;
    UCHAR Checksum;
    UCHAR OEMID[6];
    UCHAR OEMTableID[8];
    ULONG OEMRevision;
    UCHAR CreatorID[4];
    ULONG CreatorRev;
};

typedef struct _FACS {
    ULONG Signature;
    ULONG Length;
    ULONG HardwareSignature;
    ULONG pFirmwareWakingVector;
    ULONG GlobalLock;
    ULONG Flags;
    union _LARGE_INTEGER x_FirmwareWakingVector;
    UCHAR version;
    UCHAR Reserved[31];
};

typedef struct _FADT {
    struct _DESCRIPTION_HEADER Header;
    ULONG facs;
    ULONG dsdt;
    UCHAR int_model;
    UCHAR pm_profile;
    USHORT sci_int_vector;
    ULONG smi_cmd_io_port;
    UCHAR acpi_on_value;
    UCHAR acpi_off_value;
    UCHAR s4bios_req;
    UCHAR pstate_control;
    ULONG pm1a_evt_blk_io_port;
    ULONG pm1b_evt_blk_io_port;
    ULONG pm1a_ctrl_blk_io_port;
    ULONG pm1b_ctrl_blk_io_port;
    ULONG pm2_ctrl_blk_io_port;
    ULONG pm_tmr_blk_io_port;
    ULONG gp0_blk_io_port;
    ULONG gp1_blk_io_port;
    UCHAR pm1_evt_len;
    UCHAR pm1_ctrl_len;
    UCHAR pm2_ctrl_len;
    UCHAR pm_tmr_len;
    UCHAR gp0_blk_len;
    UCHAR gp1_blk_len;
    UCHAR gp1_base;
    UCHAR cstate_control;
    USHORT lvl2_latency;
    USHORT lvl3_latency;
    USHORT flush_size;
    USHORT flush_stride;
    UCHAR duty_offset;
    UCHAR duty_width;
    UCHAR day_alarm_index;
    UCHAR month_alarm_index;
    UCHAR century_alarm_index;
    USHORT boot_arch;
    UCHAR reserved3[1];
    ULONG flags;
    struct _GEN_ADDR reset_reg;
    UCHAR reset_val;
    UCHAR reserved4[3];
    union _LARGE_INTEGER x_firmware_ctrl;
    union _LARGE_INTEGER x_dsdt;
    struct _GEN_ADDR x_pm1a_evt_blk;
    struct _GEN_ADDR x_pm1b_evt_blk;
    struct _GEN_ADDR x_pm1a_ctrl_blk;
    struct _GEN_ADDR x_pm1b_ctrl_blk;
    struct _GEN_ADDR x_pm2_ctrl_blk;
    struct _GEN_ADDR x_pm_tmr_blk;
    struct _GEN_ADDR x_gp0_blk;
    struct _GEN_ADDR x_gp1_blk;
};

typedef struct _GENERAL_LOOKASIDE {
    struct _SLIST_HEADER ListHead;
    USHORT Depth;
    USHORT MaximumDepth;
    ULONG TotalAllocates;
    ULONG AllocateMisses;
    ULONG AllocateHits;
    ULONG TotalFrees;
    ULONG FreeMisses;
    ULONG FreeHits;
    enum _POOL_TYPE Type;
    ULONG Tag;
    ULONG Size;
    PVOID *Allocate;
    PVOID Free;
    struct _LIST_ENTRY ListEntry;
    ULONG LastTotalAllocates;
    ULONG LastAllocateMisses;
    ULONG LastAllocateHits;
    ULONG Future[2];
};

typedef struct _GEN_ADDR {
    UCHAR AddressSpaceID;
    UCHAR BitWidth;
    UCHAR BitOffset;
    UCHAR Reserved;
    union _LARGE_INTEGER Address;
};

typedef struct _IOAPIC {
    UCHAR Type;
    UCHAR Length;
    UCHAR IOAPICID;
    UCHAR Reserved;
    ULONG IOAPICAddress;
    ULONG SystemVectorBase;
};

typedef struct _IOSAPIC {
    UCHAR Type;
    UCHAR Length;
    USHORT Reserved;
    ULONG SystemVectorBase;
    ULONG64 IOSAPICAddress;
};

typedef struct _IO_NMISOURCE {
    UCHAR Type;
    UCHAR Length;
    USHORT Flags;
    ULONG GlobalSystemInterruptVector;
};

typedef struct _ISA_VECTOR {
    UCHAR Type;
    UCHAR Length;
    UCHAR Bus;
    UCHAR Source;
    ULONG GlobalSystemInterruptVector;
    USHORT Flags;
};

typedef struct _KDEVICE_QUEUE {
    SHORT Type;
    SHORT Size;
    struct _LIST_ENTRY DeviceListHead;
    ULONG64 Lock;
    UCHAR Busy;
    LONG64 Reserved : 8;
    LONG64 Hint : 56;
};

typedef struct _LIST_ENTRY {
    struct _LIST_ENTRY *Flink;
    struct _LIST_ENTRY *Blink;
};

typedef struct _LOCAL_NMISOURCE {
    UCHAR Type;
    UCHAR Length;
    UCHAR ProcessorID;
    USHORT Flags;
    UCHAR LINTIN;
};

typedef struct _MAPIC {
    struct _DESCRIPTION_HEADER Header;
    ULONG LocalAPICAddress;
    ULONG Flags;
    ULONG APICTables[1];
};

typedef struct _NPAGED_LOOKASIDE_LIST {
    struct _GENERAL_LOOKASIDE L;
};

typedef struct _OBJECT_ATTRIBUTES {
    ULONG Length;
    PVOID RootDirectory;
    struct _UNICODE_STRING *ObjectName;
    ULONG Attributes;
    PVOID SecurityDescriptor;
    PVOID SecurityQualityOfService;
};

typedef struct _OBJECT_TYPE {
};

typedef struct _PAGED_LOOKASIDE_LIST {
    struct _GENERAL_LOOKASIDE L;
};

typedef struct _PLATFORM_INTERRUPT {
    UCHAR Type;
    UCHAR Length;
    USHORT Flags;
    UCHAR InterruptType;
    UCHAR APICID;
    UCHAR ACPIEID;
    UCHAR IOSAPICVector;
    ULONG GlobalVector;
    ULONG Reserved;
};

typedef struct _PROCLOCALAPIC {
    UCHAR Type;
    UCHAR Length;
    UCHAR ACPIProcessorID;
    UCHAR APICID;
    ULONG Flags;
};

typedef struct _PROCLOCALSAPIC {
    UCHAR Type;
    UCHAR Length;
    UCHAR ACPIProcessorID;
    UCHAR APICID;
    UCHAR APICEID;
    UCHAR Reserved[3];
    ULONG Flags;
};

typedef struct _RSDP {
    ULONG64 Signature;
    UCHAR Checksum;
    UCHAR OEMID[6];
    UCHAR Revision;
    ULONG RsdtAddress;
    ULONG Length;
    union _LARGE_INTEGER XsdtAddress;
    UCHAR XChecksum;
    UCHAR Reserved[3];
};

typedef struct _RSDT_32 {
    struct _DESCRIPTION_HEADER Header;
    ULONG Tables[1];
};

typedef struct _RTL_BITMAP {
    ULONG SizeOfBitMap;
    PULONG Buffer;
};

typedef struct _SLIST_HEADER {
    ULONG64 Alignment;
    ULONG64 Region;
};

typedef struct _UNICODE_STRING {
    USHORT Length;
    USHORT MaximumLength;
    PUSHORT Buffer;
};

typedef union _LARGE_INTEGER {
    ULONG LowPart;
    LONG HighPart;
    struct {
        ULONG LowPart;
        LONG HighPart;
    } u;
    LONG64 QuadPart;
};

typedef union _ULARGE_INTEGER {
    ULONG LowPart;
    ULONG HighPart;
    struct {
        ULONG LowPart;
        ULONG HighPart;
    } u;
    ULONG64 QuadPart;
};

typedef enum _INTERLOCKED_RESULT {
    ResultNegative = 1,
    ResultZero = 0,
    ResultPositive = 2
};

typedef enum _MEMORY_CACHING_TYPE_ORIG {
    MmFrameBufferCached = 2
};

typedef enum _MEMORY_TYPE {
    MemoryExceptionBlock = 0,
    MemorySystemBlock = 1,
    MemoryFree = 2,
    MemoryBad = 3,
    MemoryLoadedProgram = 4,
    MemoryFirmwareTemporary = 5,
    MemoryFirmwarePermanent = 6,
    MemoryFreeContiguous = 7,
    MemorySpecialMemory = 8,
    MemoryMaximum = 9
};

typedef enum _POOL_TYPE {
    NonPagedPool = 0,
    PagedPool = 1,
    NonPagedPoolMustSucceed = 2,
    DontUseThisType = 3,
    NonPagedPoolCacheAligned = 4,
    PagedPoolCacheAligned = 5,
    NonPagedPoolCacheAlignedMustS = 6,
    MaxPoolType = 7,
    NonPagedPoolSession = 32,
    PagedPoolSession = 33,
    NonPagedPoolMustSucceedSession = 34,
    DontUseThisTypeSession = 35,
    NonPagedPoolCacheAlignedSession = 36,
    PagedPoolCacheAlignedSession = 37,
    NonPagedPoolCacheAlignedMustSSession = 38
};

Amd64PriofileInterface;
Amd64ProfileSourceDescriptorTable;
BadIOAddrList;
CounterStatus;
CurTiledCr3LowPart;
DefaultPriofileInterface;
DefaultProfileSourceDescriptor;
EM64TCounterDescriptor;
EM64TESCRDescriptor;
EM64THyperThreadingActive;
EM64TPriofileInterface;
EM64TProfileContext;
EM64TProfileSourceDescriptors;
EisaNMIMsg;
False;
GUID_BUS_INTERFACE_STANDARD;
GUID_FDMA_INTERFACE_PRIVATE;
GUID_ISA_FDMA_INTERFACE;
GUID_TARGET_DEVICE_QUERY_REMOVE;
GUID_TRANSLATOR_INTERFACE_STANDARD;
HalAcpiDispatchTable;
HalDisableFirmwareMapper;
HalDispatchTable;
HalHardwareIdString;
HalName;
HalPrivateDispatchTable;
Halp1stPhysicalPageVaddr;
Halp8259Counts;
HalpAccountingLock;
HalpAcpiCountDown;
HalpAcpiCountReset;
HalpAcpiFlags;
HalpAcpiMultiNode;
HalpAcpiNvsData;
HalpAcpiSrat;
HalpAcpiTableCacheList;
HalpAcpiTableCacheLock;
HalpAcpiTableMatchList;
HalpActiveProcessors;
HalpAddressUsageList;
HalpAllocationDescriptorArray;
HalpApicErrorLog;
HalpApicMaxCluster;
HalpApicTable;
HalpApicUsage;
HalpAuthenticAMD;
HalpBarrier;
HalpBroadcastContext;
HalpBroadcastFunction;
HalpBroadcastLock;
HalpBroadcastTargets;
HalpBroken440BX;
HalpBrokenAcpiTimer;
HalpBusType;
HalpCallbackRecord;
HalpClockMode;
HalpClockWorkUnion;
HalpCmosBusParameterTable;
HalpCmosCenturyOffset;
HalpComIoSpace;
HalpComPortIrqMapping;
HalpCr4Exists;
HalpCurrentClockRateAdjustment;
HalpCurrentClockRateIn100ns;
HalpCurrentIpiRate;
HalpCurrentRTCRegisterA;
HalpCurrentTime;
HalpCurrentTimePort;
HalpDebugPortTable;
HalpDefaultApicDestinationModeMask;
HalpDefaultInterruptAffinity;
HalpDefaultPcIoSpace;
HalpDevLevel;
HalpDevPolarity;
HalpDisableHibernate;
HalpDisableNvsSaveRestore;
HalpDisableS5Hibernation;
HalpDmaAdapterList;
HalpDmaAdapterListLock;
HalpDmaChannelState;
HalpDmaGrowMapBufferWorkerQueued;
HalpDmaHibernateAdapter;
HalpDmaHibernateRegisterSetIndex;
HalpDmaHibernateRegisterSets;
HalpDmaOperations;
HalpDoingCrashDump;
HalpDontStartProcessors;
HalpDriverObject;
HalpEisaAdapter;
HalpEisaControlBase;
HalpEisaDma;
HalpEisaELCR;
HalpEisaIoSpace;
HalpEisaIrqIgnore;
HalpEisaIrqMask;
HalpFDMAAvail;
HalpFDMAChecked;
HalpFDMAInterface;
HalpFakePciBusData;
HalpFakePciBusHandler;
HalpFeatureBits;
HalpFixedAcpiDescTable;
HalpForceApicPhysicalDestinationMode;
HalpForceClusteredApicMode;
HalpGenuineIntel;
HalpGetInfoFromACPI;
HalpGlobal8259Mask;
HalpGlobalVolatile;
HalpHardwareLockFlags;
HalpHardwareTimeRollover;
HalpHeapStart;
HalpHiberInProgress;
HalpHiberProcState;
HalpHybridApicPhysicalTargets;
HalpHyperThreadingEnabled;
HalpIDTUsage;
HalpIDTUsageFlags;
HalpINTItoVector;
HalpIOApicVersion;
HalpImcrIoSpace;
HalpInitLevel;
HalpInitialClockRateIndex;
HalpIntDestMap;
HalpInterruptObjectList;
HalpIntiInfo;
HalpInvalidAcpiTable;
HalpIoApicId;
HalpIoCompatibleRangeList0;
HalpIoCompatibleRangeList1;
HalpIoControlBase;
HalpIoMemoryBase;
HalpIpiClock;
HalpIpiPhysicalApicId;
HalpIpiPhysicalTargetMask;
HalpIpiPhysicalTargets;
HalpIpiRoutine;
HalpIpiTargetLookup;
HalpIpiTargetMask;
HalpIrqlTablesInitialized;
HalpKInterruptHeap;
HalpKInterruptHeapUsed;
HalpLocalApicErrorCount;
HalpLocalApicErrorLock;
HalpLocalNmiSources;
HalpLowStub;
HalpLowStubPhysicalAddress;
HalpMachineType;
HalpMaxApicInti;
HalpMaxHotPlugMemoryAddress;
HalpMaxNode;
HalpMaxPciBus;
HalpMaxProcs;
HalpMaxProcsPerCluster;
HalpMcaScanTime;
HalpMinPciBus;
HalpMotherboardState;
HalpMoveMemory;
HalpMpInfoTable;
HalpNMIDumpFlag;
HalpNMIInProgress;
HalpNewAdapter;
HalpNextMSRate;
HalpNodeInterruptCount;
HalpNodePriorityLevelUsage;
HalpNodeProcessorAffinity;
HalpNumaConfig;
HalpNumaLastRangeIndex;
HalpNumaMemoryNode;
HalpNumaMemoryRanges;
HalpNumberOfProcessorsInCluster;
HalpNvsVirtualAddress;
HalpOutstandingScatterGatherCount;
HalpOwnedDisplayBeforeSleep;
HalpPCIConfigInitialized;
HalpPCIConfigLock;
HalpPICINTToVector;
HalpPMStub;
HalpPciDebuggingDevice;
HalpPciIrqMask;
HalpPciLockSettings;
HalpPerfInterruptHandler;
HalpPhysicalMemoryMayAppearAbove4GB;
HalpPicStateIntact;
HalpPicVectorFlags;
HalpPicVectorRedirect;
HalpPiix4;
HalpPiix4BusNumber;
HalpPiix4DevActB;
HalpPiix4SlotNumber;
HalpProc0TSCHz;
HalpProcLocalApicTable;
HalpProcessedACPIPhase0;
HalpProcessorPCR;
HalpProcessorsNotHalted;
HalpProfileInterface;
HalpProfileRunning;
HalpProfileTimerHandler;
HalpPteForFlush;
HalpRMStub;
HalpRateCorrection;
HalpRebootNow;
HalpRtcRegA;
HalpRtcRegB;
HalpRtcTimeIncrements;
HalpSerialLen;
HalpSerialNumber;
HalpShutdownContext;
HalpSimpleBootFlagTable;
HalpSleepContext;
HalpSleepPage16Lock;
HalpSleepPageLock;
HalpSleepSync;
HalpStallLoopsPerTick;
HalpStaticIntAffinity;
HalpStaticProcLocalApicTable;
HalpSystemHardwareLock;
HalpSzBreak;
HalpSzClockLevel;
HalpSzForceClusterMode;
HalpSzInterruptAffinity;
HalpSzMaxApicCluster;
HalpSzOneCpu;
HalpSzPciLock;
HalpSzSerialNumber;
HalpSzSystem;
HalpSzTimerRes;
HalpSzUse8254;
HalpSzUsePhysicalApic;
HalpSzUsePmTimer;
HalpTemporaryLogicalProcessorToApicIdMap;
HalpTiledCr3Addresses;
HalpTimeBias;
HalpTimerWatchdogEnabled;
HalpTimerWatchdogStorageOverflow;
HalpUsePmTimer;
HalpUsedAllocDescriptors;
HalpVectorInit;
HalpVectorToINTI;
HalpVectorToIRQL;
HalpVirtAddrForFlush;
HalpWAETDeviceFlags;
HalpWakeVector;
HalpWakeupState;
HalpX86BiosInitialized;
HiberFreeCR3;
HotPatchBuffer;
IoAdapterObjectType;
KdComPortInUse;
KdDebuggerEnabled;
KdDebuggerNotPresent;
KiBugCheckData;
LastKnownGood;
LessThan16Mb;
MasterAdapter24;
MasterAdapter32;
McaBlockErrorClearing;
McaDeviceContext;
McaDriverExceptionCallback;
McaEnableCmc;
McaMutex;
McaNoBugCheck;
McaNumberOfBanks;
McaSavedAffinity;
McaSavedBankNumber;
McaSavedStatus;
McaSavedTimeStamp;
McaStatusCount;
McaWmiCallback;
MpHalHardwareIdString;
MsgMCEPending;
PCIConfigHandler;
PCIConfigHandlerType1;
PCIConfigHandlerType2;
PCIDeref;
PciIrqRoutingInterface;
PciIsaIrq;
PmAcpiDispatchTable;
True;
UserSpecifiedCpuCount;
XmBitCount;
XmCmosAddress;
XmContext;
XmEmulatorInitialized;
XmGetPciData;
XmNumberPciBusses;
XmOpcodeControlTable1;
XmOpcodeControlTable2;
XmOpcodeFunctionTable;
XmOperandDecodeTable;
XmPCIConfigAddress;
XmPciBiosPresent;
XmSetPciData;
_IMPORT_DESCRIPTOR_KDCOM;
_IMPORT_DESCRIPTOR_ntoskrnl;
_NULL_IMPORT_DESCRIPTOR;
_imp_DbgBreakPoint;
_imp_DbgPrint;
_imp_ExAcquireFastMutex;
_imp_ExAllocatePoolWithTag;
_imp_ExCreateCallback;
_imp_ExFreePoolWithTag;
_imp_ExQueueWorkItem;
_imp_ExRegisterCallback;
_imp_ExReleaseFastMutex;
_imp_ExpInterlockedPopEntrySList;
_imp_ExpInterlockedPushEntrySList;
_imp_HalDispatchTable;
_imp_HalPrivateDispatchTable;
_imp_InbvAcquireDisplayOwnership;
_imp_InbvCheckDisplayOwnership;
_imp_InbvDisplayString;
_imp_InbvEnableDisplayString;
_imp_InbvInstallDisplayStringFilter;
_imp_InbvIsBootDriverInstalled;
_imp_InbvResetDisplay;
_imp_InbvSetScrollRegion;
_imp_InbvSetTextColor;
_imp_InbvSolidColorFill;
_imp_InitializeSListHead;
_imp_IoAdapterObjectType;
_imp_IoAllocateMdl;
_imp_IoAssignDriveLetters;
_imp_IoAssignResources;
_imp_IoAttachDeviceToDeviceStack;
_imp_IoBuildSynchronousFsdRequest;
_imp_IoCreateDevice;
_imp_IoCreateDriver;
_imp_IoDeleteDevice;
_imp_IoFreeMdl;
_imp_IoGetDeviceInterfaces;
_imp_IoGetDeviceObjectPointer;
_imp_IoReadPartitionTable;
_imp_IoRegisterPlugPlayNotification;
_imp_IoReportDetectedDevice;
_imp_IoReportHalResourceUsage;
_imp_IoSetPartitionInformation;
_imp_IoWritePartitionTable;
_imp_IofCallDriver;
_imp_IofCompleteRequest;
_imp_KdDebuggerEnabled;
_imp_KdDebuggerNotPresent;
_imp_KdRestore;
_imp_KeAcquireInStackQueuedSpinLock;
_imp_KeAcquireInStackQueuedSpinLockAtDpcLevel;
_imp_KeAcquireSpinLockAtDpcLevel;
_imp_KeAcquireSpinLockRaiseToDpc;
_imp_KeBugCheckEx;
_imp_KeEnterKernelDebugger;
_imp_KeFindConfigurationNextEntry;
_imp_KeInitializeDeviceQueue;
_imp_KeInitializeDpc;
_imp_KeInitializeEvent;
_imp_KeInitializeInterrupt;
_imp_KeInsertDeviceQueue;
_imp_KeInsertQueueDpc;
_imp_KeProfileInterruptWithSource;
_imp_KeQueryActiveProcessors;
_imp_KeQueryMultiThreadProcessorSet;
_imp_KeQueryPrcbAddress;
_imp_KeRegisterBugCheckCallback;
_imp_KeReleaseInStackQueuedSpinLock;
_imp_KeReleaseInStackQueuedSpinLockFromDpcLevel;
_imp_KeReleaseSpinLock;
_imp_KeReleaseSpinLockFromDpcLevel;
_imp_KeRemoveDeviceQueue;
_imp_KeRevertToUserAffinityThread;
_imp_KeSaveStateForHibernate;
_imp_KeSetEvent;
_imp_KeSetImportanceDpc;
_imp_KeSetProfileIrql;
_imp_KeSetSystemAffinityThread;
_imp_KeSetTargetProcessorDpc;
_imp_KeSetTimeIncrement;
_imp_KeTestSpinLock;
_imp_KeTryToAcquireSpinLockAtDpcLevel;
_imp_KeUpdateSystemTime;
_imp_KeWaitForSingleObject;
_imp_KiBugCheckData;
_imp_KiCpuId;
_imp_MmAllocateContiguousMemory;
_imp_MmAllocateContiguousMemorySpecifyCache;
_imp_MmAllocateMappingAddress;
_imp_MmAllocatePagesForMdl;
_imp_MmFreeContiguousMemory;
_imp_MmFreeContiguousMemorySpecifyCache;
_imp_MmFreeMappingAddress;
_imp_MmFreePagesFromMdl;
_imp_MmGetPhysicalAddress;
_imp_MmLockPagableDataSection;
_imp_MmMapIoSpace;
_imp_MmMapLockedPagesSpecifyCache;
_imp_MmMapLockedPagesWithReservedMapping;
_imp_MmUnlockPagableImageSection;
_imp_MmUnmapIoSpace;
_imp_MmUnmapLockedPages;
_imp_MmUnmapReservedMapping;
_imp_ObCreateObject;
_imp_ObInsertObject;
_imp_ObReferenceObjectByPointer;
_imp_ObfDereferenceObject;
_imp_ObfReferenceObject;
_imp_PoSetHiberRange;
_imp_PoStartNextPowerIrp;
_imp_PsGetCurrentProcessId;
_imp_RtlClearBits;
_imp_RtlCopyMemoryNonTemporal;
_imp_RtlFindClearBitsAndSet;
_imp_RtlInitUnicodeString;
_imp_RtlInitializeBitMap;
_imp_RtlIntegerToUnicodeString;
_imp_RtlNumberOfClearBits;
_imp_RtlQueryRegistryValues;
_imp_RtlSetAllBits;
_imp_RtlTimeFieldsToTime;
_imp_RtlTimeToTimeFields;
_imp_ZwClose;
_imp_ZwCreateKey;
_imp_ZwEnumerateValueKey;
_imp_ZwOpenKey;
_imp_ZwPowerInformation;
_imp_ZwQueryKey;
_imp_ZwQueryValueKey;
_imp_ZwSetValueKey;
_imp___C_specific_handler;
_imp__setjmp;
_imp__stricmp;
_imp_atoi;
_imp_longjmp;
_imp_strncmp;
_imp_strncpy;
_imp_strstr;
_imp_swprintf;
_security_cookie;
rgzApicNotVerified;
rgzBadApicVersion;
rgzBadDefault;
rgzBadHal;
rgzConfigurationData;
rgzEnableCMC;
rgzEnableMCA;
rgzEnableMCE;
rgzIdentifier;
rgzMPPTRCheck;
rgzMPSBadCheck;
rgzMPSBadSig;
rgzMultiFunctionAdapter;
rgzNoApic;
rgzNoApicTable;
rgzNoMCABugCheck;
rgzNoMPTable;
rgzNoMem;
rgzNoMpsTable;
rgzPCICardList;
rgzPCIIdentifier;
rgzRTCNotFound;
rgzReservedResources;
rgzSessionManager;
rgzSuspendCallbackName;
x86BiosFrameBuffer;
x86BiosInitialized;
x86BiosIoMemory;
x86BiosIoSpace;
x86BiosLowMemory;
x86BiosScratchMemory;
x86BiosTransferLength;
x86BiosTransferMemory;
KDCOM_NULL_THUNK_DATA;
ntoskrnl_NULL_THUNK_DATA;

Amd64DisableMonitoring();
Amd64EnableMonitoring();
Amd64GetProfileDescriptor();
Amd64InitializeProfiling();
Amd64OverflowHandler();
Amd64QueryInformation();
Amd64SetInterval();
DbgBreakPoint();
DbgPrint();
DefaultDisableMonitoring();
DefaultEnableMonitoring();
DefaultInitializeProfiling();
DefaultOverflowHandler();
DefaultQueryInformation();
DefaultSetInterval();
DetectAcpiMP();
EM64TAllocateRegisters();
EM64TDisableMonitoring();
EM64TEnableMonitoring();
EM64TGetProfileDescriptor();
EM64TInitializeProfiling();
EM64TOverflowHandler();
EM64TQueryInformation();
EM64TSetInterval();
HalAcpiGetTable();
HalAcpiTimerCarry();
HalAcquireDisplayOwnership();
HalAdjustResourceList();
HalAllProcessorsStarted();
HalAllocateAdapterChannel();
HalAllocateCommonBuffer();
HalAllocateCrashDumpRegisters();
HalAssignSlotResources();
HalBuildMdlFromScatterGatherList();
HalBuildScatterGatherList();
HalCalculateScatterGatherListSize();
HalCalibratePerformanceCounter();
HalCallBios();
HalClearSoftwareInterrupt();
HalDisableSystemInterrupt();
HalDisplayString();
HalEnableSystemInterrupt();
HalFlushCommonBuffer();
HalFreeCommonBuffer();
HalGetAdapter();
HalGetBusData();
HalGetBusDataByOffset();
HalGetDmaAlignment();
HalGetEnvironmentVariable();
HalGetInterruptVector();
HalGetScatterGatherList();
HalHandleMcheck();
HalHandleNMI();
HalInitSystem();
HalInitializeProcessor();
HalIrqTranslateResourceRequirementsRoot();
HalIrqTranslateResourcesRoot();
HalIsHyperThreadingEnabled();
HalMakeBeep();
HalPnpGetDmaAdapter();
HalPnpInterfaceDereference();
HalPnpInterfaceReference();
HalProcessorIdle();
HalPutDmaAdapter();
HalPutScatterGatherList();
HalQueryDisplayParameters();
HalQueryRealTimeClock();
HalReadDmaCounter();
HalRealAllocateAdapterChannel();
HalReportResourceUsage();
HalRequestIpi();
HalRequestSoftwareInterrupt();
HalReturnToFirmware();
HalSendNMI();
HalSendSoftwareInterrupt();
HalSetBusData();
HalSetBusDataByOffset();
HalSetDisplayParameters();
HalSetEnvironmentVariable();
HalSetProfileInterval();
HalSetRealTimeClock();
HalSetTimeIncrement();
HalStartNextProcessor();
HalStartProfileInterrupt();
HalStopProfileInterrupt();
HalSystemVectorDispatchEntry();
HalTranslateBusAddress();
HalTranslatorDereference();
HalTranslatorReference();
HalWriteBootRegister();
HalaAcpiTimerInit();
HalacpiGetInterruptTranslator();
HalacpiIrqTranslateResourceRequirementsIsa();
HalacpiIrqTranslateResourcesIsa();
HaliAcpiMachineStateInit();
HaliAcpiQueryFlags();
HaliAcpiSleep();
HaliAcpiTimerInit();
HaliGetDmaAdapter();
HaliHaltSystem();
HaliHandlePCIConfigSpaceAccess();
HaliInitPnpDriver();
HaliInitPowerManagement();
HaliIsVectorValid();
HaliLocateHiberRanges();
HaliPciInterfaceReadConfig();
HaliPciInterfaceWriteConfig();
HaliQuerySystemInformation();
HaliSetMaxLegacyPciBusNumber();
HaliSetSystemInformation();
HaliSetVectorState();
HaliSetWakeAlarm();
HaliSetWakeEnable();
HalpAcpiCacheOverrideTables();
HalpAcpiCopyBiosTable();
HalpAcpiDetectMachineSpecificActions();
HalpAcpiEnableClockInterrupt();
HalpAcpiFindRsdtPhase0();
HalpAcpiGetTable();
HalpAcpiGetTableFromBios();
HalpAcpiIBMExaMatch();
HalpAcpiIBMVigilMatch();
HalpAcpiPicStateIntact();
HalpAcpiPostSleep();
HalpAcpiPreSleep();
HalpAcpiSanityCheckOverrideTables();
HalpAcpiTableCacheInit();
HalpAcquireCmosSpinLock();
HalpAcquireCmosSpinLockAndWait();
HalpAcquireHighLevelLock();
HalpAddAdapterToList();
HalpAddDevice();
HalpAddInterruptDest();
HalpAllocPhysicalMemory();
HalpAllocateAdapterCallback();
HalpAllocateMapRegisters();
HalpAllocateSystemInterruptVector();
HalpApicRebootService();
HalpApicSpuriousService();
HalpAssignDriveLetters();
HalpAssignPCISlotResources();
HalpAssignSlotResources();
HalpBiosDisplayReset();
HalpBroadcastCallService();
HalpBugCheckCallback();
HalpBuildIpiDestinationMap();
HalpBuildRealModeStartBlock();
HalpBuildResumeStructures();
HalpBuildTiledCR3Ex();
HalpCheckPowerButton();
HalpCheckWakeupTimeAndAdjust();
HalpClockInterrupt();
HalpClockInterruptStub();
HalpClockInterruptWork();
HalpCmosReadByte();
HalpCmosWriteByte();
HalpCommitCR3Worker();
HalpConfigureCardBusBridge();
HalpCreateInterrupt();
HalpDisablePicInti();
HalpDisableRedirEntry();
HalpDispatchPnp();
HalpDispatchPower();
HalpDispatchWmi();
HalpDmaAcquireBufferMappings();
HalpDmaAllocateChildAdapter();
HalpDmaAllocateContiguousMemory();
HalpDmaAllocateContiguousPagesFromContiguousPool();
HalpDmaAllocateContiguousPagesFromContiguousPoolAtHighLevel();
HalpDmaAllocateEmergencyResources();
HalpDmaAllocateLocalContiguousPool();
HalpDmaAllocateLocalScatterPool();
HalpDmaAllocateMapRegisters();
HalpDmaAllocateMapRegistersAtHighLevel();
HalpDmaAllocateMappingResources();
HalpDmaAllocateNewTranslationBuffer();
HalpDmaAllocateReservedMappingArray();
HalpDmaAllocateScatterPagesFromContiguousPool();
HalpDmaAllocateScatterPagesFromContiguousPoolAtHighLevel();
HalpDmaAllocateScatterPagesFromScatterPool();
HalpDmaAllocateTranslationBuffer();
HalpDmaCommitContiguousMapBuffers();
HalpDmaCommitScatterMapBuffers();
HalpDmaFinalizeDoubleBufferingDisposition();
HalpDmaFlushScatterTransfer();
HalpDmaFreeChildAdapter();
HalpDmaFreeChildAdapterWorker();
HalpDmaFreeCrashDumpRegisters();
HalpDmaGetTranslationEntries();
HalpDmaGrowContiguousMapBuffers();
HalpDmaGrowScatterMapBuffers();
HalpDmaInitializeMasterAdapter();
HalpDmaMapScatterTransfer();
HalpDmaNextContiguousPiece();
HalpDmaPrependTranslations();
HalpDmaQueueAdapter();
HalpDmaReturnPageToOwner();
HalpDmaReturnPageToSource();
HalpDmaReturnToContiguousPool();
HalpDmaSyncMapBuffers();
HalpDmaSyncMapBuffersWithEmergencyResources();
HalpDmaZeroMapBuffers();
HalpDriverEntry();
HalpDynamicSystemResourceConfiguration();
HalpECmosReadByte();
HalpECmosWriteByte();
HalpEnableLocalNmiSources();
HalpEnableNMI();
HalpEnablePerfInterupt();
HalpEnablePicInti();
HalpEnableRedirEntry();
HalpEndOfBoot();
HalpFDMANotificationCallback();
HalpFindBusAddressTranslation();
HalpFindFreeResourceLimits();
HalpFixupPhysicalIntiDestinations();
HalpFreeNvsBuffers();
HalpFreeResumeStructures();
HalpFreeTiledCR3WorkRoutine();
HalpFreeTiledCR3Worker();
HalpGenericCall();
HalpGetAcpiStaticNumaTopology();
HalpGetApicInterruptDesc();
HalpGetApicVersion();
HalpGetChipHacks();
HalpGetCmosData();
HalpGetDisplayBiosInformation();
HalpGetEisaData();
HalpGetIoApicId();
HalpGetMcaLog();
HalpGetNMICrashFlag();
HalpGetNextProcessorApicId();
HalpGetPCIData();
HalpGetParameters();
HalpGetSystemInterruptVector();
HalpGrowMapBufferWorker();
HalpHalt();
HalpInitBootTable();
HalpInitIntiInfo();
HalpInitMP();
HalpInitMpInfo();
HalpInitializeApicAddressing();
HalpInitializeClock();
HalpInitializeIOUnits();
HalpInitializeIrqlTables();
HalpInitializeLocalUnit();
HalpInitializePICs();
HalpInitializePciStubs();
HalpIoDelay();
HalpKdStallExecution();
HalpLMIdentityStub();
HalpLMIdentityStubEnd();
HalpLMStub();
HalpLocalApicErrorService();
HalpMapCR3Ex();
HalpMapNvsArea();
HalpMapPhysicalMemory64();
HalpMapPhysicalMemoryWriteThrough64();
HalpMapTransfer();
HalpMarkProcessorStarted();
HalpMaskAcpiInterrupt();
HalpMcaInit();
HalpMcaReadProcessorException();
HalpMcaReadRegisterInterface();
HalpNumaInitializeStaticConfiguration();
HalpNumaQueryPageToNode();
HalpNumaQueryProcessorNode();
HalpPCIISALine2Pin();
HalpPCIPin2ISALine();
HalpPCIReadUcharType1();
HalpPCIReadUcharType2();
HalpPCIReadUlongType1();
HalpPCIReadUlongType2();
HalpPCIReadUshortType1();
HalpPCIReadUshortType2();
HalpPCIReleaseSynchronzationType1();
HalpPCIReleaseSynchronzationType2();
HalpPCISynchronizeType1();
HalpPCISynchronizeType2();
HalpPCIWriteUcharType1();
HalpPCIWriteUcharType2();
HalpPCIWriteUlongType1();
HalpPCIWriteUlongType2();
HalpPCIWriteUshortType1();
HalpPCIWriteUshortType2();
HalpPassIrpFromFdoToPdo();
HalpPerfInterrupt();
HalpPhase0GetPciDataByOffset();
HalpPhase0SetPciDataByOffset();
HalpPiix4Detect();
HalpPmTimerScaleTimers();
HalpPostSleepMP();
HalpPowerStateCallback();
HalpPreserveNvsArea();
HalpProfileInterrupt();
HalpPutAcpiHacksInRegistry();
HalpQueryAcpiResourceRequirements();
HalpQueryDeviceRelations();
HalpQueryIdFdo();
HalpQueryIdPdo();
HalpQueryInterface();
HalpQueryPciRegistryInfo();
HalpQueryResources();
HalpQueueMapBufferWorker();
HalpReadCmosTime();
HalpReadLocalApicID();
HalpReadPCIConfig();
HalpReadPartitionTable();
HalpReboot();
HalpRegisterPciDebuggingDeviceInfo();
HalpReleaseHighLevelLock();
HalpReleasePciDeviceForDebugging();
HalpReportResourceUsage();
HalpResetAllProcessors();
HalpResetSBF();
HalpResetThisProcessor();
HalpRestoreDmaControllerState();
HalpRestoreInterruptControllerState();
HalpRestoreNvsArea();
HalpSaveContextTargetProcessor();
HalpSaveDmaControllerState();
HalpSaveProcessorStateAndWait();
HalpScaleTimers();
HalpSearchForPciDebuggingDevice();
HalpSendFlatIpi();
HalpSendNodeIpi64();
HalpSendPhysicalIpi();
HalpSet8259Mask();
HalpSetClockAfterSleep();
HalpSetClockBeforeSleep();
HalpSetCmosData();
HalpSetHandlerAddressToIDTIrql();
HalpSetInterruptControllerWakeupState();
HalpSetPCIData();
HalpSetPartitionInformation();
HalpSetPmTimerFunction();
HalpSetProfileSourceInterval();
HalpSetRedirEntry();
HalpSetSystemInformation();
HalpSetWakeAlarm();
HalpSetupAcpiPhase0();
HalpSetupPciDeviceForDebugging();
HalpSetupRealModeResume();
HalpSetupUnconfiguredDebuggingDevice();
HalpStartProcessor();
HalpStopOhciInterrupt();
HalpStopUhciInterrupt();
HalpStoreFreeCr3();
HalpTranslateBusAddress();
HalpUnconfigureCardBusBridge();
HalpUnconfigurePciBridge();
HalpUnmapVirtualAddress();
HalpUnmaskAcpiInterrupt();
HalpValidPCISlot();
HalpValidateCardbusSocketRegs();
HalpWaitForPending();
HalpWhackICHUsbSmi();
HalpWriteCmosTime();
HalpWritePCIConfig();
HalpWritePartitionTable();
HalpWriteResetCommand();
IoFlushAdapterBuffers();
IoFreeAdapterChannel();
IoFreeMapRegisters();
IoMapTransfer();
KdRestore();
KeFlushWriteBuffer();
KeQueryPerformanceCounter();
KeStallExecutionProcessor();
PicInterruptHandlerInt();
PicNopHandlerInt();
PicSpuriousService37();
RtlMoveMemory();
XmAaaOp();
XmAadOp();
XmAamOp();
XmAasOp();
XmAccumImmediate();
XmAccumRegister();
XmAdcOp();
XmAddOp();
XmAddOperands();
XmAndOp();
XmBitScanGeneral();
XmBoundOp();
XmBsfOp();
XmBsrOp();
XmBswapOp();
XmBtOp();
XmBtcOp();
XmBtrOp();
XmBtsOp();
XmByteImmediate();
XmCallOp();
XmCbwOp();
XmClcOp();
XmCldOp();
XmCliOp();
XmCmcOp();
XmCmpOp();
XmCmpsOp();
XmCmpxchgOp();
XmCompareOperands();
XmCwdOp();
XmDaaOp();
XmDasOp();
XmDecOp();
XmDivOp();
XmEffectiveOffset();
XmEmulateStream();
XmEnterOp();
XmEvaluateAddressSpecifier();
XmEvaluateIndexSpecifier();
XmExecuteInt1a();
XmFlagsRegister();
XmGeneralBitOffset();
XmGeneralRegister();
XmGetImmediateSourceValue();
XmGetLongImmediate();
XmGetSignedByteImmediateToLong();
XmGetSignedByteImmediateToWord();
XmGetWordImmediate();
XmGroup1General();
XmGroup1Immediate();
XmGroup2By1();
XmGroup2ByByte();
XmGroup2ByCL();
XmGroup3General();
XmGroup45General();
XmGroup7General();
XmGroup8BitOffset();
XmHltOp();
XmIdivOp();
XmIllOp();
XmImmediateEnter();
XmImmediateJump();
XmImulImmediate();
XmImulOp();
XmImulxOp();
XmInOp();
XmIncOp();
XmInsOp();
XmInt1aFindPciClassCode();
XmInt1aFindPciDevice();
XmInt1aReadConfigRegister();
XmInt1aWriteConfigRegister();
XmIntOp();
XmIretOp();
XmJcxzOp();
XmJmpOp();
XmJxxOp();
XmLahfOp();
XmLeaveOp();
XmLoadSegment();
XmLodsOp();
XmLongJump();
XmLoopOp();
XmMovOp();
XmMoveGeneral();
XmMoveImmediate();
XmMoveRegImmediate();
XmMoveSegment();
XmMoveXxGeneral();
XmMovsOp();
XmMulOp();
XmNegOp();
XmNoOperands();
XmNopOp();
XmNotOp();
XmOpcodeEscape();
XmOpcodeRegister();
XmOrOp();
XmOutOp();
XmOutsOp();
XmPopGeneral();
XmPopOp();
XmPopaOp();
XmPortDX();
XmPortImmediate();
XmPrefixOpcode();
XmPushImmediate();
XmPushOp();
XmPushPopSegment();
XmPushaOp();
XmRclOp();
XmRcrOp();
XmRdtscOp();
XmRetOp();
XmRolOp();
XmRorOp();
XmSahfOp();
XmSarOp();
XmSbbOp();
XmScasOp();
XmSegmentOffset();
XmSetccByte();
XmShiftDouble();
XmShlOp();
XmShldOp();
XmShortJump();
XmShrOp();
XmShrdOp();
XmSmswOp();
XmStcOp();
XmStdOp();
XmStiOp();
XmStosOp();
XmStringOperands();
XmSubOp();
XmSubOperands();
XmSxxOp();
XmTestOp();
XmXaddOp();
XmXchgOp();
XmXlatOpcode();
XmXorOp();
_C_specific_handler();
_security_check_cookie();
atoi();
longjmp();
memcmp();
memcpy();
memmove();
memset();
setjmp();
stricmp();
strncmp();
strncpy();
strstr();
swprintf();
x86BiosExecuteInterrupt();
x86BiosGetPciBusData();
x86BiosInitializeBiosEx();
x86BiosInitializeBiosShadowed();
x86BiosReadCmosPort();
x86BiosReadIoSpace();
x86BiosReadPciDataPort();
x86BiosSetPciBusData();
x86BiosTranslateAddress();
x86BiosWriteCmosPort();
x86BiosWriteIoSpace();
x86BiosWritePciAddressPort();
